# Generated by Django 2.0.13 on 2019-04-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0002_auto_20190417_1257'),
        ('post', '0002_auto_20190412_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hid',
            field=models.ManyToManyField(to='hashtag.Hashtag'),
        ),
    ]
